services:
  postgres:
    image: postgres:17
    container_name: wikiaim-postgres
    environment:
      POSTGRES_USER: wikiaim
      POSTGRES_PASSWORD: wikipass
      POSTGRES_DB: wikiaim
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: