micronaut:
  application:
    name: wikiaim-backend
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()

datasources:
  default:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wikiaim}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:wikiaim}
    password: ${DB_PASSWORD:}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
        format_sql: true

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
